Remove edge channel option from aura-channel-set and update error message link in aura-update

diff --git a/bin/aura-update b/bin/aura-update
--- a/bin/aura-update
+++ b/bin/aura-update
@@ -2,7 +2,7 @@
 
 set -e
 
-trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://aura.org/discord\033[0m"' ERR
+trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://github.com/CjLogic/Aura/discussions/categories/q-a\033[0m"' ERR
 
 if [[ $1 == "-y" ]] || aura-update-confirm; then
   aura-update-without-idle
